spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/maptriz
    username: maptriz
    password: ewqiop321
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
liquibase:
  change-log: classpath:/db/db-changelog-main.xml